services:
  structurizr-lite:
    image: structurizr/structurizr:latest
    container_name: structurizr-lite
    command: ["local"]
    ports:
      - "8088:8080"
    volumes:
      - ../../structurizr:/usr/local/structurizr
    networks:
      - shared
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
    name: tg-chat-history-analyser_default
