apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: notification-platform
servers: 1
agents: 1
ports:
  - port: 3000:3000
    nodeFilters:
      - loadbalancer
  - port: 9095:9090
    nodeFilters:
      - loadbalancer

