spring:
  application:
    name: profile-consent
  config:
    import: optional:classpath:creds/user-creds.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${postgresql.url:jdbc:postgresql://localhost:25432/main_db?currentSchema=nf_prof}
    username: ${postgresql.user.username:user}
    password: ${postgresql.user.password:password}
  flyway:
    locations: classpath:db/migration
  data:
    redis:
      host: ${PROFILE_CONSENT_REDIS_HOST:localhost}
      port: ${PROFILE_CONSENT_REDIS_PORT:6379}
      username: ${PROFILE_CONSENT_REDIS_USERNAME:redisuser}
      password: ${PROFILE_CONSENT_REDIS_PASSWORD:redisuserpassword}
      timeout: 3s
      connect-timeout: 3s

app:
  profile-consent:
    storage:
      type: ${PROFILE_CONSENT_STORAGE_TYPE:postgres}

profile-consent:
  redis:
    key-prefix: ${PROFILE_CONSENT_REDIS_KEY_PREFIX:profile-consent:recipient:}

grpc:
  server:
    port: ${PROFILE_CONSENT_GRPC_PORT:9096}

server:
  port: ${SERVER_PORT:8913}

management:
  health:
    redis:
      enabled: ${PROFILE_CONSENT_REDIS_HEALTH_ENABLED:false}
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    ru.batoyan.vkr.notification.profile: DEBUG
