#services:
#  mai-proj-app:
#    build:
#      context: ../../
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - main_db
#      - kafka
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://main_db:5432/main_db
#      SPRING_DATASOURCE_USERNAME: ${MAIN_DB_USERNAME:-postgres}
#      SPRING_DATASOURCE_PASSWORD: ${MAIN_DB_PASSWD:-postgres}
#    networks:
#      - shared
#
#volumes:
  #app_backups:
