name: Deploy on VM

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and deploy on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.VM_SSH_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/own_apps/notifcation-platform-gradle-groovy
            git pull --ff-only
            cd deploy
            docker compose up -d --remove-orphans
